job1:
   type: build
   script:
    - module_path=`git config --get remote.origin.url`
    - module_path=`echo $module_path | awk -F/ '{print $(NF-1),$NF }' | tr " " /`
    - /usr/local/bin/python2.7 /usr/local/bin/sypen.py -b $CI_BUILD_REF_NAME -m $module_path -d modules
   tags:
    - runner_puppy_gridka